# Generated by Django 3.0.1 on 2019-12-30 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('headline', models.CharField(max_length=250)),
                ('about', models.TextField()),
                ('github', models.CharField(max_length=150)),
                ('linkedin', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('website', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='user_profiles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('startdate', models.DateField()),
                ('endate', models.DateField()),
                ('desc', models.TextField(blank=True)),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getdetails.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getdetails.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('startdate', models.DateField()),
                ('endate', models.DateField()),
                ('desc', models.TextField(blank=True)),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getdetails.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('startdate', models.DateField()),
                ('endate', models.DateField()),
                ('link', models.CharField(max_length=150)),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getdetails.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('startdate', models.DateField()),
                ('endate', models.DateField()),
                ('desc', models.TextField(blank=True)),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getdetails.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('startdate', models.DateField()),
                ('endate', models.DateField()),
                ('desc', models.TextField(blank=True)),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getdetails.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('org', models.CharField(max_length=100)),
                ('issuedate', models.DateField()),
                ('expiration', models.DateField()),
                ('cred_id', models.CharField(max_length=100)),
                ('cred_url', models.CharField(max_length=150)),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getdetails.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('org', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('desc', models.TextField(blank=True)),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getdetails.UserInfo')),
            ],
        ),
    ]
