# Generated by Django 3.0.1 on 2019-12-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='template_val',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
