# Generated by Django 3.0.1 on 2020-01-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdetails', '0002_userinfo_template_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='cred_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='cred_url',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
