# Generated by Django 3.0.1 on 2020-01-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdetails', '0003_auto_20200102_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='course',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='specialization',
            field=models.CharField(default='BE', max_length=100),
            preserve_default=False,
        ),
    ]
