# Generated by Django 3.0.1 on 2019-12-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displayTemplates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='value',
            field=models.CharField(default=None, max_length=101),
            preserve_default=False,
        ),
    ]
