# Generated by Django 3.0.1 on 2019-12-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displayTemplates', '0002_template_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='img',
            field=models.ImageField(upload_to='../displayTemplates/template_icons'),
        ),
    ]
