# Generated by Django 3.0.1 on 2019-12-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displayTemplates', '0004_auto_20191229_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='img',
            field=models.ImageField(upload_to='template_icons'),
        ),
    ]
